package entidades;
// Generated 14/07/2019 07:08:16 PM by Hibernate Tools 4.3.1



/**
 * Sexo generated by hbm2java
 */
public class Sexo  implements java.io.Serializable {


     private int idsexo;
     private char descripcion;
     private char estado;

    public Sexo() {
    }

    public Sexo(int idsexo, char descripcion, char estado) {
       this.idsexo = idsexo;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public int getIdsexo() {
        return this.idsexo;
    }
    
    public void setIdsexo(int idsexo) {
        this.idsexo = idsexo;
    }
    public char getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(char descripcion) {
        this.descripcion = descripcion;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }




}


